---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint-dev
  namespace: octoprint-dev
  labels:
    app: octoprint-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi